name: CI

on:
  pull_request:
  push:

concurrency:
  group: dlc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1

  go_test:
    name: go_test
    runs-on: ubuntu-latest
    services:
      selefra_postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test
          POSTGRES_USER: postgres
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
      - name: go_test
        env:
          TZ: Asia/Shanghai
          SELEFRA_DATABASE_DSN: "host=127.0.0.1 user=postgres password=pass port=5432 dbname=test sslmode=disable"
        run: go test ./...